FROM python:3.12-slim


WORKDIR /app


RUN apt-get update && apt-get install -y \
    libnss3 \
    libatk-bridge2.0-0 \
    libgtk-3-0 \
    libgbm1 \
    && rm -rf /var/lib/apt/lists/*


COPY requirements.txt .


RUN pip install -r requirements.txt


RUN playwright install chromium


COPY . .


CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]