services:

  crawler:
    build:
      context: .
      dockerfile: Dockerfile

    image: crawler:latest
    container_name: crawler

    working_dir: /service

    environment:
      PYTHONUNBUFFERED: "1"

    command:
      [
        "uv",
        "run",
        "python",
        "-m",
        "application.main"
      ]

    restart: "no"

    networks:
      - ai-network


  crawler-dev:
    build:
      context: .
      dockerfile: Dockerfile

    image: crawler:dev
    container_name: crawler-dev

    working_dir: /service

    environment:
      PYTHONUNBUFFERED: "1"

    volumes:
      - ./:/service:rw
      - crawler-dev-venv:/service/.venv

    command:
      [
        "uv",
        "run",
        "python",
        "-m",
        "application.main"
      ]

    restart: "no"

    networks:
      - ai-network


volumes:
  crawler-dev-venv:


networks:
  ai-network:
    external: true