version: "3.9"

services:
  service-scrapy-example:
    build:
      context: .
      dockerfile: Dockerfile
    image: service-scrapy-example:latest
    container_name: service-scrapy-example
    ports:
      - "8001:8001"
    restart: unless-stopped
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    volumes:
      - ./:/service
    command: ["uv", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001"]

    networks:

      - ai-network

networks:

  ai-network:

    external: true
