"""
init after refactor

Revision ID: 1833864cda3b
Revises: 
Create Date: 2025-08-04 14:20:04.563095

Project   : MyBlog FastAPI System
Author    : Gold Zheng
Alembic   : Auto-generated by Alembic Migration System
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Revision identifiers, used by Alembic.
revision: str = '1833864cda3b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """
    Upgrade migrations:
    Write your upgrade logic here.
    For example:
        op.create_table(...)
        op.add_column(...)
        op.create_index(...)
    """
    pass


def downgrade() -> None:
    """
    Downgrade migrations:
    Write your downgrade logic here.
    This is the reverse of upgrade().
    """
    pass
