# 构建阶段
FROM node:20-alpine AS build

ENV NODE_ENV=production
WORKDIR /app

# 注意加上 frontend 路径前缀
COPY frontend/package.json ./
COPY frontend/pnpm-lock.yaml ./

RUN npm install -g pnpm
RUN pnpm install

# 拷贝前端源码
COPY frontend/ .

# 构建
RUN pnpm build

# 部署阶段
FROM nginx:alpine

RUN mkdir -p /etc/nginx/ssl

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
